update cicd.yml

diff --git a/.github/workflows/CICD-dev-AWS.yml b/.github/workflows/CICD-dev-AWS.yml
--- a/.github/workflows/CICD-dev-AWS.yml
+++ b/.github/workflows/CICD-dev-AWS.yml
@@ -112,19 +112,19 @@ jobs:
           echo "tag_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
           echo "image_uri=${{ env.ECR_URI }}:${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
 
-      - name: Wait for image in ECR
-        run: |
-          for i in {1..12}; do
-            if aws ecr describe-images \
-              --repository-name "${{ env.ECR_REPO }}" \
-              --image-ids imageTag="${{ steps.meta.outputs.tag_sha }}" >/dev/null 2>&1; then
-              echo "Image found: ${{ env.ECR_REPO }}:${{ steps.meta.outputs.tag_sha }}"
-              exit 0
-            fi
-            echo "Waiting for image ${{ env.ECR_REPO }}:${{ steps.meta.outputs.tag_sha }}... ($i/12)"
-            sleep 5
-          done
-          echo "Image not found in time"; exit 1
+      # - name: Wait for image in ECR
+      #   run: |
+      #     for i in {1..12}; do
+      #       if aws ecr describe-images \
+      #         --repository-name "${{ env.ECR_REPO }}" \
+      #         --image-ids imageTag="${{ steps.meta.outputs.tag_sha }}" >/dev/null 2>&1; then
+      #         echo "Image found: ${{ env.ECR_REPO }}:${{ steps.meta.outputs.tag_sha }}"
+      #         exit 0
+      #       fi
+      #       echo "Waiting for image ${{ env.ECR_REPO }}:${{ steps.meta.outputs.tag_sha }}... ($i/12)"
+      #       sleep 5
+      #     done
+      #     echo "Image not found in time"; exit 1
 
       - name: Export current task definition
         run: |
